version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: us
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: deltaq123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spring-net

  app:
    build: .
    container_name: spring_app_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/us
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: deltaq123
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - spring-net

volumes:
  pgdata: {}

networks:
  spring-net: {}
