name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  setup:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/setup-compose-action@v1.2.0
    - name: Build the Docker image
      run:  docker-compose up --build

