name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1.2.0

      - name: Maven Set up
        uses: hb0730/maven-action@v1.0.2
        
      - name: Maven builds
        run: mvn clean package -DskipTests
      
      - name: Build and run containers
        run: docker compose up --build -d

      - name: Show running containers
        run: docker ps
